---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.2.3
    hooks:
      - id: check-ast
      - id: check-symlinks
      - id: check-executables-have-shebangs
      - id: check-merge-conflict
      - id: check-yaml
        args: [--unsafe]
      - id: detect-private-key
      - id: double-quote-string-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch # No (direct) commits to master
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v1.3.0
    hooks:
    -   id: add-trailing-comma
  - repo: git://github.com/Lucas-C/pre-commit-hooks-markup
    sha: v1.0.0
    hooks:
    -   id: rst-linter
