dist: bionic
language: python

env:
  - WORKON_HOME=.pipenv/venvs
  - PIP_CACHE_DIR=.pipenv/pipcache

cache:
  directories:
    - .pipenv

python:
  - "3.8"

branches:
  only:
  - dev

before_install:
  - sudo apt-get install -y optipng
addons:
  apt:
    update: true

install:
  - make install-ci
script:
  - make html

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  local_dir: ./output
  target_branch: master
  on:
    branch: dev

notifications:
  email:
    on_success: change
    on_failure: always
